services:
  - type: web
    name: asset-simulator
    plan: free
    rootDir: apps/server
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    buildFilter:
      paths:
        - apps/api/**

  - type: web
    name: asset-simulator-web
    rootDir: apps/web
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
    buildFilter:
      paths:
        - apps/web/**
        - packages/shared/**