services:
  - type: web
    name: asset-simulator
    runtime: node
    region: oregon
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm run clean && npm ci --cache /tmp/empty-cache && npx turbo run build --filter=@asset-simulator/shared --filter=web --filter=server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_KEY
        sync: false
