name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Render Registry
      uses: docker/login-action@v3
      with:
        registry: registry.app.render.com
        username: ${{ secrets.RENDER_SERVICE_ID }}
        password: ${{ secrets.RENDER_API_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        target: production
        tags: registry.app.render.com/${{ secrets.RENDER_SERVICE_ID }}/asset-simulator:latest
        build-args: |
          REACT_APP_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          REACT_APP_SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true
